### ISSUE TITLE
窗口拖动严重滞后

### ISSUE THREAD

**Issue by CodingOctocat** [zdy1988/IconPark.Xaml#2]
应该和 `GlassesWindow` 有关，也可能和系统有关。我在公司笔记本上拖拽窗口正常，家里电脑拖拽滞后，几乎无法使用。

受影响版本：1.3.0、1.3.0-rc

家里电脑：
版本	Windows 11 专业版
版本	22H2
安装日期	‎2022/‎10/‎5 ‎星期三
操作系统版本	22621.1778
体验	Windows Feature Experience Pack 1000.22642.1000.0

公司电脑：
版本	Windows 11 家庭中文版
版本	22H2
安装日期	‎2023/‎3/‎13 ‎星期一
操作系统版本	22621.1702
体验	Windows Feature Experience Pack 1000.22641.1000.0

**Comment by zdy1988** [comment]
Hi！

我没有win11的环境，我两台电脑都是win10，一台配置好，一台配置差点儿，但都不滞后，因为拖动代码的实现很简单，GlassesWindow的原理[使用 SetWindowCompositionAttribute 来控制程序的窗口边框和背景](https://blog.walterlv.com/post/set-window-composition-attribute)是调用这个固定的Windows API

或者你试试这个项目[FluentWPF](https://github.com/sourcechord/FluentWPF)，我想你做WPF应该对这个不陌生...

如果还是效果不好，可能是电脑配置问题？如果是API问题，改天我扒一扒WINUI的代码瞧瞧...

**Comment by CodingOctocat** [comment]
和电脑配置无关，我家里的台式机配置比公司笔记本高了N个档次，我用过 HandyControl，它的 Demo 中的自定义窗口也会这样滞后，而且用我公司笔记本也会，我查了下很有可能是这种带特效的 窗口+Win11 的问题。

**Comment by zdy1988** [comment]
还真是，那我换个不透明的window吧，反正这个半透明也没什么用...
