### ISSUE TITLE
哈哈哈哈哈, 这..移动鼠标去点弹窗功能,但是鼠标移开了图标,弹窗就消失了

### ISSUE THREAD

**Issue by YuniqueUnic** [zdy1988/IconPark.Xaml#3]
![image](https://github.com/zdy1988/IconPark.Xaml/assets/127641096/ad790ecb-7c08-4c7e-b61d-f012b7a38be9)
哈哈哈哈哈, 这..移动鼠标去点弹窗功能,但是鼠标移开了图标,弹窗就消失了....

> **太痛苦了. 什么太阳能手电筒....**

**Comment by zdy1988** [comment]
先将就用横视图吧，下次给你整个舒服的！

**Comment by YuniqueUnic** [comment]
哈哈哈哈, 用不了. 根本点不到悬浮窗功能..

**Comment by zdy1988** [comment]
我发布了 1.3.2 ，看看这次你舒服了没！

**Comment by YuniqueUnic** [comment]
可以用了,感谢.😀
