### ISSUE TITLE
[功能请求] 新增直接复制原始的 ViewBox Path XAML 代码

### ISSUE THREAD

**Issue by CodingOctocat** [zdy1988/IconPark.Xaml#4]
有时程序就可能只用到 1 个图标，不是很想单独引用一个图标包，所以能否增加一个直接复制 ViewBox Path XAML 代码的功能？

```XAML
<Viewbox>
    <Path Tag="图标的名称" Data="..." />
</Viewbox>
```
另外，可以为 `Path` 的 `Tag` 附加图标的名称以便代码可阅读。

现在我是翻阅 [src/IconPark.Xaml/IconDataFactory.cs](https://github.com/zdy1988/IconPark.Xaml/blob/master/src/IconPark.Xaml/IconDataFactory.cs)  来手动完成这个工作。

**Comment by zdy1988** [comment]
我发布了 1.3.2 ，试试吧！
